#release configuration
#Tue Aug 11 15:04:31 CEST 2026
projectVersionPolicyId=default
project.rel.ch.unige.biochem\:bigdataviewer-omezarr-adapter=0.1.0
project.scm.ch.unige.biochem\:bigdataviewer-omezarr-adapter.connection=scm\:git\:https\://github.com/unige-biochem/bdvplayground-omezarr-adapter
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.ch.unige.biochem\:bigdataviewer-omezarr-adapter.developerConnection=scm\:git\:git@github.com\:unige-biochem/bdvplayground-omezarr-adapter
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.ch.unige.biochem\:bigdataviewer-omezarr-adapter.tag=HEAD
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.scm.ch.unige.biochem\:bigdataviewer-omezarr-adapter.url=https\://github.com/unige-biochem/bdvplayground-omezarr-adapter
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
project.dev.ch.unige.biochem\:bigdataviewer-omezarr-adapter=0.1.1-SNAPSHOT
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/unige-biochem/bdvplayground-omezarr-adapter
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=bigdataviewer-omezarr-adapter-0.1.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
